BethanysPieShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BethanysPieShop/Controllers/PieController.cs
using BethanysPieShop.Models.Entities;
using BethanysPieShop.Models.Interfaces;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        //public ViewResult List()
        //{
        //    PiesListViewModel piesList = new PiesListViewModel();
        //    piesList.Pies = _pieRepository.AllPies;

        //    piesList.CurrentCategory = "Cheese cake";
        //    return View(piesList);
        //}

        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.PieId);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }


        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);

            if(pie == null)
                return NotFound();
            return View(pie);
        }
    }
}

BethanysPieShop/Controllers/ShoppingCartController.cs
using BethanysPieShop.Models.Entities;
using BethanysPieShop.Models.Interfaces;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace BethanysPieShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        
        private readonly IPieRepository _pieRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IPieRepository pieRepository, ShoppingCart shoppingCart)
        {
            _pieRepository = pieRepository;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.AllPies.FirstOrDefault(p => p.PieId == pieId);

            if (selectedPie != null)
            {
                _shoppingCart.AddToCart(selectedPie, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.AllPies.FirstOrDefault(p => p.PieId == pieId);

            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }
    }
}

BethanysPieShop/Views/Shared/_Carousel.cshtml
<div id="carouselExampleControls" class="carousel slide mb-5" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="/img/carousel1.jpg" class="d-block" alt="...">
        </div>
        <div class="carousel-item">
            <img src="/img/carousel2.jpg" class="d-block" alt="...">
        </div>
        <div class="carousel-item">
            <img src="/img/carousel3.jpg" class="d-block" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

BethanysPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/Style.css" asp-append-version="true" />
    <link rel = "stylesheet" href = "~/lib/font-awesome/css/all.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;700&display=swap" rel="stylesheet"> 
</head>
<body>
    @*navbar*@
    <nav class="navbar navbar-expand-lg fixed-top navbar-custom">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"> <img class="img-logo" alt="Bethany's Pie Shop'" src="~/img/bethanylogo.png" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav align-items-center">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    @await Component.InvokeAsync("CategoryMenu")
                    @await Component.InvokeAsync("ShoppingCartSummary")
                    <li class="nav-item">
                        <a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a>
                    </li>
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>

   
     <div class="container">
          @RenderBody()
    </div>
    <footer></footer>

    @*js*@
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

BethanysPieShop/Views/Shared/_PieCard.cshtml
@model Pie


<div class="card">
    <img src="@Model.ImageThumbnailUrl" alt="">
    <div class="box-details">
        <span class="badge rounded-pill text-bg-warning text-end">@Model.Price.ToString("c")</span>
        <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId" class="name-pie">@Model.Name</a>
        <p>@Model.ShortDescription</p>
    </div>
    <div class="addToCart">
        <p class="button">
            <a class="btn btn-primary" 
            asp-controller="ShoppingCart" 
            asp-action="AddToShoppingCart"
            asp-route-pieId="@Model.PieId">Add to cart</a>
        </p>
    </div>
</div>